[tool.isort]
# Formatting
combine_as_imports = true
combine_star = true
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
order_by_type = true
use_parentheses = true

# Files
not_skip = [
    "__init__.py",
    "__main__.py",
]

# Sections
default_section = "THIRDPARTY"
known_stdlib = [
    "typing",
]
known_django = [
    "django",
]
known_first_party = [
    "glass2netlify",
]
sections = [
    "FUTURE",
    "STDLIB",
    "DJANGO",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
